version: "3"

services:
  blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ${SOURCE_PATH}:/root/work/blog
    ports:
      - 3000:3000
      - 8080:8080
